#!/usr/bin/env python3
import os
import sys

main_path = os.path.expanduser("~/GOODS-DRAGON/main.py")
if not os.path.exists(main_path):
    print("Error: main.py not found. Please ensure GOODS-DRAGON is installed in ~/GOODS-DRAGON")
    sys.exit(1)
sys.argv[0] = "dragon"
exec(open(main_path).read())
