#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import os
from datetime import datetime
from core.logger import log_info, log_success

class AdvancedReport:
    def __init__(self, json_file, output_dir="reports/"):
        self.json_file = json_file
        self.output_dir = output_dir
        self.data = {}
        self.base_name = os.path.splitext(os.path.basename(json_file))[0]

    def load_data(self):
        try:
            with open(self.json_file, 'r', encoding='utf-8') as f:
                self.data = json.load(f)
            return True
        except Exception as e:
            log_info(f"Error loading JSON: {e}")
            return False

    def generate_html(self):
        """تولید گزارش HTML پیشرفته با نمودار و تحلیل"""
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>GOODS-DRAGON - Advanced Report</title>
            <style>
                body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #0d1117; color: #c9d1d9; padding: 20px; }}
                .container {{ max-width: 1200px; margin: auto; background: #161b22; padding: 25px; border-radius: 12px; }}
                h1 {{ color: #58a6ff; }}
                .header {{ border-bottom: 2px solid #30363d; padding-bottom: 10px; margin-bottom: 20px; }}
                .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px; margin: 20px 0; }}
                .card {{ background: #21262d; padding: 15px; border-radius: 8px; border-left: 4px solid #58a6ff; }}
                .card h3 {{ margin: 0 0 5px 0; color: #58a6ff; }}
                .card p {{ margin: 0; font-size: 24px; font-weight: bold; }}
                .card.danger {{ border-left-color: #f85149; }}
                .card.warning {{ border-left-color: #d29922; }}
                .card.success {{ border-left-color: #3fb950; }}
                pre {{ background: #0d1117; padding: 15px; border-radius: 8px; overflow-x: auto; }}
                .footer {{ margin-top: 30px; text-align: center; color: #8b949e; border-top: 1px solid #30363d; padding-top: 15px; }}
            </style>
        </head>
        <body>
        <div class="container">
            <div class="header">
                <h1>🐉 GOODS-DRAGON - Advanced Security Report</h1>
                <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                <p><strong>Author:</strong> zeus (z4) | @iM_z4</p>
            </div>
            
            <div class="grid">
                <div class="card success">
                    <h3>Total Scans</h3>
                    <p>{len(self.data)}</p>
                </div>
                <div class="card">
                    <h3>Target</h3>
                    <p style="font-size: 16px;">{self.data.get('target', 'N/A')}</p>
                </div>
                <div class="card warning">
                    <h3>Risk Level</h3>
                    <p style="font-size: 18px;">{self._calculate_risk()}</p>
                </div>
            </div>
            
            <h2>📋 Scan Results</h2>
            <pre>{json.dumps(self.data, indent=2, ensure_ascii=False)}</pre>
            
            <div class="footer">
                <p>Report generated by <strong>GOODS-DRAGON</strong> v1.0</p>
            </div>
        </div>
        </body>
        </html>
        """
        path = f"{self.output_dir}{self.base_name}_advanced.html"
        with open(path, 'w', encoding='utf-8') as f:
            f.write(html)
        log_success(f"Advanced HTML report: {path}")

    def _calculate_risk(self):
        """محاسبه سطح ریسک کلی"""
        risk_score = 0
        for key, value in self.data.items():
            if isinstance(value, dict):
                if 'vulnerable_count' in value:
                    risk_score += value['vulnerable_count']
                if 'total_found' in value:
                    risk_score += value['total_found'] // 2
        if risk_score > 20:
            return "🔴 Critical"
        elif risk_score > 10:
            return "🟠 High"
        elif risk_score > 5:
            return "🟡 Medium"
        else:
            return "🟢 Low"

    def generate_pdf(self):
        """تولید PDF پیشرفته (با reportlab)"""
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.pdfgen import canvas
            path = f"{self.output_dir}{self.base_name}_advanced.pdf"
            c = canvas.Canvas(path, pagesize=letter)
            c.drawString(100, 750, "🐉 GOODS-DRAGON - Advanced Security Report")
            c.drawString(100, 730, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
            c.drawString(100, 710, f"Author: zeus (z4) | @iM_z4")
            c.drawString(100, 680, f"Target: {self.data.get('target', 'N/A')}")
            c.drawString(100, 660, f"Risk Level: {self._calculate_risk()}")
            c.save()
            log_success(f"Advanced PDF report: {path}")
        except Exception as e:
            log_info(f"PDF generation skipped: {e}")

    def generate_all(self):
        if not self.load_data():
            return
        os.makedirs(self.output_dir, exist_ok=True)
        self.generate_html()
        self.generate_pdf()
