#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
from datetime import datetime
from core.logger import log_info, log_success

class HackerOneReport:
    def __init__(self, json_file, output_file="hackerone_report.md"):
        self.json_file = json_file
        self.output_file = output_file
        self.data = {}

    def load_data(self):
        try:
            with open(self.json_file, 'r', encoding='utf-8') as f:
                self.data = json.load(f)
            return True
        except Exception as e:
            log_info(f"Error loading JSON: {e}")
            return False

    def generate(self):
        """Generate HackerOne format report"""
        if not self.load_data():
            return

        report = f"""# 🐉 Dragon Eye - Security Assessment Report

**HackerOne Style Report**
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Author:** zeus (z4) | @iM_z4

---

## 📋 Executive Summary

This report was generated by **Dragon Eye v1.0**, an automated security assessment tool.

**Target:** {self.data.get('target', 'N/A')}

---

## 🔍 Vulnerability Summary

| Severity | Type | Count |
| :--- | :--- | :--- |
"""

        severity_counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0, "Info": 0}
        
        for scan_type, results in self.data.items():
            if isinstance(results, dict):
                vulnerabilities = results.get('vulnerabilities', results.get('results', []))
                if isinstance(vulnerabilities, list):
                    for vuln in vulnerabilities:
                        if isinstance(vuln, dict):
                            severity = vuln.get('severity', 'Info')
                            if severity in severity_counts:
                                severity_counts[severity] += 1

        for severity, count in severity_counts.items():
            if count > 0:
                report += f"| {severity} | {severity} | {count} |\n"

        report += f"""

---

## 🚨 Detailed Findings

"""

        for scan_type, results in self.data.items():
            if isinstance(results, dict):
                report += f"### {scan_type.replace('_', ' ').title()}\n\n"
                report += f"```json\n{json.dumps(results, indent=2, ensure_ascii=False)}\n```\n\n"

        report += f"""

---

## 📌 Recommendations

1. **Critical/High issues**: Address immediately
2. **Medium issues**: Address in the next sprint
3. **Low/Info issues**: Consider fixing in future releases

---

## 📊 Assessment Metadata

| Attribute | Value |
| :--- | :--- |
| **Tool** | Dragon Eye v1.0 |
| **Author** | zeus (z4) |
| **Telegram** | @iM_z4 |
| **Report Date** | {datetime.now().strftime('%Y-%m-%d')} |

---

**Disclaimer:** This report is for authorized security testing only.
"""

        with open(self.output_file, 'w', encoding='utf-8') as f:
            f.write(report)
        log_success(f"HackerOne style report generated: {self.output_file}")
