#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
from datetime import datetime
from core.logger import log_info, log_success

class HTMLReport:
    def __init__(self, json_file, output_file="report.html"):
        self.json_file = json_file
        self.output_file = output_file
        self.data = {}

    def load_data(self):
        try:
            with open(self.json_file, 'r', encoding='utf-8') as f:
                self.data = json.load(f)
            return True
        except Exception as e:
            log_info(f"Error loading JSON: {e}")
            return False

    def generate_markdown(self):
        """Generate Markdown report for bug bounty platforms"""
        md = f"""# 🐉 Dragon Eye - Security Assessment Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Author:** zeus (z4) | @iM_z4

---

## 📊 Executive Summary

| Scan Type | Findings |
| :--- | :--- |
"""
        total_findings = 0
        for scan_type, results in self.data.items():
            if isinstance(results, dict):
                count = results.get('vulnerable_count', results.get('total_found', results.get('total', 0)))
                total_findings += count if isinstance(count, int) else 0
                md += f"| {scan_type.replace('_', ' ').title()} | {count} |\n"
        
        md += f"\n**Total Findings:** {total_findings}\n\n---\n\n## 🔍 Detailed Findings\n\n"

        for scan_type, results in self.data.items():
            if isinstance(results, dict):
                md += f"### {scan_type.replace('_', ' ').title()}\n\n"
                md += f"```json\n{json.dumps(results, indent=2, ensure_ascii=False)}\n```\n\n"

        md += f"""
---

## 📌 Report Generated By

- **Tool:** Dragon Eye v1.0
- **Author:** zeus (z4)
- **Telegram:** @iM_z4

---
*This report is for authorized security testing only.*
"""
        return md

    def generate_html(self):
        """Generate HTML report with professional styling"""
        if not self.load_data():
            return

        # Count vulnerabilities
        total_vulns = 0
        for key, value in self.data.items():
            if isinstance(value, dict):
                total_vulns += value.get('vulnerable_count', value.get('total_found', value.get('total', 0)))

        html = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Dragon Eye - Security Report</title>
            <style>
                body {{ 
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
                    background: #0a0a0a; 
                    color: #e0e0e0; 
                    margin: 0; 
                    padding: 20px;
                }}
                .container {{ 
                    max-width: 1200px; 
                    margin: 0 auto; 
                    background: #1a1a2e; 
                    padding: 30px; 
                    border-radius: 10px; 
                    box-shadow: 0 0 30px rgba(0,0,0,0.8);
                    border: 1px solid #2a2a4e;
                }}
                .header {{ 
                    background: linear-gradient(135deg, #0f3460, #16213e);
                    padding: 25px; 
                    border-radius: 8px; 
                    margin-bottom: 30px;
                    border-left: 4px solid #e94560;
                }}
                .header h1 {{ 
                    color: #e94560; 
                    margin: 0; 
                    font-size: 28px;
                    text-shadow: 0 0 20px rgba(233, 69, 96, 0.3);
                }}
                .header small {{ color: #8892b0; }}
                .summary {{ 
                    display: flex; 
                    gap: 20px; 
                    margin: 20px 0; 
                    flex-wrap: wrap;
                }}
                .summary-item {{ 
                    background: #16213e; 
                    padding: 15px 25px; 
                    border-radius: 8px; 
                    flex: 1; 
                    min-width: 150px;
                    border: 1px solid #2a2a4e;
                }}
                .summary-item h3 {{ margin: 0; color: #8892b0; font-size: 14px; }}
                .summary-item p {{ 
                    font-size: 28px; 
                    font-weight: bold; 
                    margin: 5px 0 0; 
                    color: #e94560;
                }}
                .scan-section {{ 
                    background: #16213e; 
                    padding: 20px; 
                    border-radius: 8px; 
                    margin: 15px 0;
                    border: 1px solid #2a2a4e;
                }}
                .scan-section h2 {{ color: #64ffda; margin-top: 0; }}
                .scan-section pre {{ 
                    background: #0a0a1a; 
                    color: #ccd6f6; 
                    padding: 15px; 
                    border-radius: 5px; 
                    overflow-x: auto; 
                    font-size: 13px; 
                    border: 1px solid #2a2a4e;
                }}
                .badge {{
                    display: inline-block;
                    padding: 3px 12px;
                    border-radius: 12px;
                    font-size: 12px;
                    font-weight: bold;
                }}
                .badge-danger {{ background: #e94560; color: white; }}
                .badge-success {{ background: #2ecc71; color: white; }}
                .badge-warning {{ background: #f39c12; color: white; }}
                .badge-info {{ background: #3498db; color: white; }}
                .footer {{ 
                    margin-top: 30px; 
                    text-align: center; 
                    color: #8892b0; 
                    font-size: 13px; 
                    border-top: 1px solid #2a2a4e; 
                    padding-top: 20px; 
                }}
                .footer a {{ color: #64ffda; text-decoration: none; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>🐉 Dragon Eye - Security Report</h1>
                    <small>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</small>
                    <br><small>Author: zeus (z4) | Telegram: @iM_z4</small>
                </div>

                <div class="summary">
                    <div class="summary-item">
                        <h3>Scans Performed</h3>
                        <p>{len(self.data)}</p>
                    </div>
                    <div class="summary-item">
                        <h3>Total Findings</h3>
                        <p>{total_vulns}</p>
                    </div>
                </div>
        """

        for scan_type, results in self.data.items():
            if not isinstance(results, dict):
                continue
            html += f"""
                <div class="scan-section">
                    <h2>🔍 {scan_type.replace('_', ' ').title()}</h2>
                    <pre>{json.dumps(results, indent=2, ensure_ascii=False)}</pre>
                </div>
            """

        html += f"""
                <div class="footer">
                    <p>Report generated by <strong>Dragon Eye</strong> v1.0 | Developed by zeus (z4)</p>
                    <p>For more info, contact <a href="https://t.me/iM_z4">@iM_z4</a></p>
                </div>
            </div>
        </body>
        </html>
        """

        with open(self.output_file, 'w', encoding='utf-8') as f:
            f.write(html)
        log_success(f"HTML report generated: {self.output_file}")

    def generate(self):
        """Generate both HTML and Markdown reports"""
        self.generate_html()
        # Save Markdown
        md_file = self.output_file.replace('.html', '.md').replace('.json', '.md')
        with open(md_file, 'w', encoding='utf-8') as f:
            f.write(self.generate_markdown())
        log_success(f"Markdown report generated: {md_file}")
