#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
from datetime import datetime
from core.logger import log_info, log_success

class ReportGenerator:
    def __init__(self, json_file, output_file="custom_report.txt"):
        self.json_file = json_file
        self.output_file = output_file

    def generate(self):
        try:
            with open(self.json_file, 'r') as f:
                data = json.load(f)
        except:
            log_info("No data found")
            return

        report = f"""
═══════════════════════════════════════════════════════════
🐉 DRAGON EYE - SECURITY ASSESSMENT REPORT
═══════════════════════════════════════════════════════════

Target: {data.get('target', 'N/A')}
Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Author: zeus (z4) | @iM_z4

═══════════════════════════════════════════════════════════
📊 EXECUTIVE SUMMARY
═══════════════════════════════════════════════════════════
"""
        total = 0
        for key, value in data.items():
            if isinstance(value, dict):
                count = value.get('total_found', value.get('total', value.get('vulnerable_count', 0)))
                total += count if isinstance(count, int) else 0
                report += f"{key.replace('_', ' ').title()}: {count}\n"

        report += f"\nTotal Issues Found: {total}\n"
        report += """

═══════════════════════════════════════════════════════════
🔍 DETAILED FINDINGS
═══════════════════════════════════════════════════════════
"""

        for key, value in data.items():
            if isinstance(value, dict):
                report += f"\n--- {key.replace('_', ' ').title()} ---\n"
                if 'vulnerabilities' in value:
                    for v in value['vulnerabilities']:
                        report += f"  • {v.get('type', 'Unknown')}: {v.get('description', 'N/A')}\n"
                elif 'results' in value:
                    for r in value['results']:
                        report += f"  • {r.get('type', 'Unknown')}: {r.get('url', 'N/A')}\n"

        report += """
═══════════════════════════════════════════════════════════
📌 RECOMMENDATIONS
═══════════════════════════════════════════════════════════
1. Address Critical and High severity issues immediately
2. Implement security headers (CSP, HSTS, XFO)
3. Review exposed sensitive files
4. Apply security patches
5. Conduct regular security assessments

═══════════════════════════════════════════════════════════
📌 REPORT GENERATED BY
═══════════════════════════════════════════════════════════
Tool: Dragon Eye v1.0
Author: zeus (z4)
Telegram: @iM_z4

═══════════════════════════════════════════════════════════
"""

        with open(self.output_file, 'w') as f:
            f.write(report)
        log_success(f"Custom report generated: {self.output_file}")
