"""
GOODS-DRAGON Smart Orchestrator
Runs professional tools and aggregates results.
"""
import subprocess
import json
import os
from datetime import datetime

class Orchestrator:
    def __init__(self, target, verbose=False):
        self.target = target
        self.verbose = verbose
        self.results = {}
    
    def run_subfinder(self):
        """Run subfinder for subdomain enumeration."""
        try:
            result = subprocess.run(["subfinder", "-d", self.target, "-silent"], 
                                   capture_output=True, text=True, timeout=120)
            subdomains = result.stdout.strip().split('\n')
            self.results['subdomains'] = [s for s in subdomains if s]
            return len(self.results['subdomains'])
        except:
            return 0
    
    def run_nuclei(self):
        """Run nuclei on discovered subdomains."""
        targets_file = f"reports/{self.target}_targets.txt"
        with open(targets_file, 'w') as f:
            f.write('\n'.join(self.results.get('subdomains', [self.target])))
        
        try:
            result = subprocess.run(
                ["nuclei", "-l", targets_file, "-severity", "critical,high", 
                 "-silent", "-json"],
                capture_output=True, text=True, timeout=300
            )
            findings = []
            for line in result.stdout.strip().split('\n'):
                if line:
                    findings.append(json.loads(line))
            self.results['nuclei_findings'] = findings
            return len(findings)
        except:
            return 0
    
    def generate_hackerone_report(self):
        """Generate a HackerOne-style report from all findings."""
        report = []
        report.append("# 🐉 GOODS-DRAGON Automated Pentest Report")
        report.append(f"**Target:** {self.target}")
        report.append(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        report.append(f"**Tool:** GOODS-DRAGON v2.0.0 (Orchestrator Mode)")
        report.append("---")
        
        # Subdomains
        report.append("## 📋 Discovered Subdomains")
        for sub in self.results.get('subdomains', []):
            report.append(f"- {sub}")
        
        # Nuclei Findings
        report.append("## 🔥 Vulnerability Findings (Nuclei)")
        for finding in self.results.get('nuclei_findings', []):
            report.append(f"### {finding.get('info', {}).get('name', 'Unknown')}")
            report.append(f"- **Severity:** {finding.get('info', {}).get('severity', 'N/A')}")
            report.append(f"- **URL:** {finding.get('matched-at', 'N/A')}")
            report.append(f"- **Description:** {finding.get('info', {}).get('description', 'N/A')}")
            report.append(f"- **Remediation:** {finding.get('info', {}).get('remediation', 'N/A')}")
        
        report.append("---")
        report.append("*Report generated by GOODS-DRAGON Orchestrator*")
        report.append("*Team: L-DRAGON | Owner: 0xL-DRAGON*")
        return '\n'.join(report)
    
    def run(self):
        """Execute the full orchestration workflow."""
        print("🐉 Starting GOODS-DRAGON Orchestrator...")
        print(f"Target: {self.target}\n")
        
        print("[1/2] Running Subfinder...")
        sub_count = self.run_subfinder()
        print(f"  ✅ Found {sub_count} subdomains")
        
        print("[2/2] Running Nuclei...")
        vuln_count = self.run_nuclei()
        print(f"  ✅ Found {vuln_count} vulnerabilities")
        
        # Generate report
        report = self.generate_hackerone_report()
        report_file = f"reports/{self.target}_hackerone_report.md"
        os.makedirs("reports", exist_ok=True)
        with open(report_file, 'w') as f:
            f.write(report)
        
        print(f"\n✅ Report saved: {report_file}")
        return report
